//! AgentControll Doctor diagnostic subsystem.
//!
//! Provides automated, read-only diagnostic checks for:
//! - System environment and XDG paths
//! - AgentControll installation and release consistency
//! - External Google Antigravity (`agy`) CLI resolution and validation
//! - AgentControll configuration, data, and cache directories
//! - SQLite accounts database health and schema
//! - Configured accounts, profiles, credentials, consistency, and isolation
//! - Ambient Google/Gemini credential detection
//! - Control daemon and session runtime health

pub mod accounts;
pub mod agy;
pub mod daemon;
pub mod environment;
pub mod format;
pub mod installation;
pub mod paths;
pub mod system;

use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// Status of an individual diagnostic check.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum CheckStatus {
    Pass,
    Warn,
    Fail,
    Info,
}

impl CheckStatus {
    pub fn is_pass(&self) -> bool {
        matches!(self, CheckStatus::Pass)
    }

    pub fn is_warn(&self) -> bool {
        matches!(self, CheckStatus::Warn)
    }

    pub fn is_fail(&self) -> bool {
        matches!(self, CheckStatus::Fail)
    }

    pub fn is_info(&self) -> bool {
        matches!(self, CheckStatus::Info)
    }
}

/// Overall health status for the entire Doctor report.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum OverallStatus {
    Healthy,
    Warnings,
    Unhealthy,
}

/// Detailed result of an individual diagnostic check.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CheckResult {
    pub id: String,
    pub title: String,
    pub status: CheckStatus,
    pub summary: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub remediation: Option<String>,
}

impl CheckResult {
    pub fn pass(
        id: impl Into<String>,
        title: impl Into<String>,
        summary: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            title: title.into(),
            status: CheckStatus::Pass,
            summary: summary.into(),
            details: None,
            remediation: None,
        }
    }

    pub fn info(
        id: impl Into<String>,
        title: impl Into<String>,
        summary: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            title: title.into(),
            status: CheckStatus::Info,
            summary: summary.into(),
            details: None,
            remediation: None,
        }
    }

    pub fn warn(
        id: impl Into<String>,
        title: impl Into<String>,
        summary: impl Into<String>,
        remediation: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            title: title.into(),
            status: CheckStatus::Warn,
            summary: summary.into(),
            details: None,
            remediation: Some(remediation.into()),
        }
    }

    pub fn fail(
        id: impl Into<String>,
        title: impl Into<String>,
        summary: impl Into<String>,
        remediation: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            title: title.into(),
            status: CheckStatus::Fail,
            summary: summary.into(),
            details: None,
            remediation: Some(remediation.into()),
        }
    }

    pub fn with_details(mut self, details: impl Into<String>) -> Self {
        self.details = Some(details.into());
        self
    }
}

/// Complete diagnostic report generated by `Doctor`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DoctorReport {
    pub status: OverallStatus,
    pub version: String,
    pub checks: Vec<CheckResult>,
}

impl DoctorReport {
    pub fn new(version: impl Into<String>, checks: Vec<CheckResult>) -> Self {
        let has_fail = checks.iter().any(|c| c.status == CheckStatus::Fail);
        let has_warn = checks.iter().any(|c| c.status == CheckStatus::Warn);
        let status = if has_fail {
            OverallStatus::Unhealthy
        } else if has_warn {
            OverallStatus::Warnings
        } else {
            OverallStatus::Healthy
        };

        Self {
            status,
            version: version.into(),
            checks,
        }
    }

    pub fn pass_count(&self) -> usize {
        self.checks.iter().filter(|c| c.status.is_pass()).count()
    }

    pub fn warn_count(&self) -> usize {
        self.checks.iter().filter(|c| c.status.is_warn()).count()
    }

    pub fn fail_count(&self) -> usize {
        self.checks.iter().filter(|c| c.status.is_fail()).count()
    }

    pub fn info_count(&self) -> usize {
        self.checks.iter().filter(|c| c.status.is_info()).count()
    }
}

/// Options controlling Doctor diagnostics.
#[derive(Debug, Clone, Default)]
pub struct DoctorOpts {
    /// Perform additional in-depth safe diagnostics.
    pub deep: bool,
    /// Return machine-readable JSON without ANSI codes.
    pub json: bool,
    /// Optional override for ~/.config/agentcontrol (useful for tests).
    pub config_dir: Option<PathBuf>,
    /// Optional override for ~/.local/share/agentcontrol (useful for tests).
    pub data_dir: Option<PathBuf>,
    /// Optional override for ~/.cache/agentcontrol (useful for tests).
    pub cache_dir: Option<PathBuf>,
    /// Optional override for HOME (useful for tests).
    pub home_dir: Option<PathBuf>,
    /// Optional override for daemon socket path.
    pub socket_path: Option<PathBuf>,
    /// Optional explicit path to `agy` binary to inspect.
    pub agy_bin: Option<PathBuf>,
}

/// Coordinator for running diagnostic checks.
pub struct Doctor {
    opts: DoctorOpts,
}

impl Doctor {
    pub fn new(opts: DoctorOpts) -> Self {
        Self { opts }
    }

    /// Resolve effective config directory.
    pub fn config_dir(&self) -> PathBuf {
        if let Some(ref d) = self.opts.config_dir {
            return d.clone();
        }
        crate::agy_auth::agentcontrol_config_dir()
    }

    /// Resolve effective data directory.
    pub fn data_dir(&self) -> PathBuf {
        if let Some(ref d) = self.opts.data_dir {
            return d.clone();
        }
        std::env::var("XDG_DATA_HOME")
            .map(|d| PathBuf::from(d).join("agentcontrol"))
            .unwrap_or_else(|_| {
                let home = self.home_dir();
                home.join(".local").join("share").join("agentcontrol")
            })
    }

    /// Resolve effective cache directory.
    pub fn cache_dir(&self) -> PathBuf {
        if let Some(ref d) = self.opts.cache_dir {
            return d.clone();
        }
        std::env::var("XDG_CACHE_HOME")
            .map(|d| PathBuf::from(d).join("agentcontrol"))
            .unwrap_or_else(|_| {
                let home = self.home_dir();
                home.join(".cache").join("agentcontrol")
            })
    }

    /// Resolve effective home directory.
    pub fn home_dir(&self) -> PathBuf {
        if let Some(ref d) = self.opts.home_dir {
            return d.clone();
        }
        std::env::var("HOME")
            .map(PathBuf::from)
            .unwrap_or_else(|_| PathBuf::from("/tmp"))
    }

    /// Resolve effective daemon socket path.
    pub fn socket_path(&self) -> PathBuf {
        if let Some(ref p) = self.opts.socket_path {
            return p.clone();
        }
        if let Ok(val) = std::env::var("AC_SOCKET") {
            if !val.trim().is_empty() {
                return PathBuf::from(val);
            }
        }
        crate::config::Config::default().socket_path
    }

    /// Run all diagnostic checks and assemble the report.
    pub async fn run_diagnostics(&self) -> DoctorReport {
        let mut checks = Vec::new();

        // 1. System checks
        system::check_system(self, &mut checks);

        // 2. Installation & version consistency
        installation::check_installation(self, &mut checks);

        // 3. Antigravity CLI resolution & validation
        agy::check_agy(self, &mut checks).await;

        // 4. AgentControll directory paths & permissions
        paths::check_paths(self, &mut checks);

        // 5. Database, Accounts, Profiles & Credentials
        accounts::check_accounts_and_profiles(self, &mut checks);

        // 6. Environment & ambient credentials
        environment::check_environment(self, &mut checks);

        // 7. Daemon & session status
        daemon::check_daemon(self, &mut checks).await;

        DoctorReport::new(env!("CARGO_PKG_VERSION"), checks)
    }

    /// Run diagnostics and format output according to options (JSON or Human).
    pub async fn execute(&self) -> (DoctorReport, String) {
        let report = self.run_diagnostics().await;
        let output = if self.opts.json {
            format::render_json(&report)
        } else {
            format::render_human(&report, self.opts.deep)
        };
        (report, output)
    }
}
